### ISSUE TITLE
Alpha Version for 1.17 [deepmoblearning-refabricated-0.4.0-alpha1]

### ISSUE THREAD

**Issue by KavisKryptic** [NathanPB/DeepMobLearning-Refabricated#43]
(I'm just reposting what I said on the comments of https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated#c50)

So when I was testing with my modpack, I ran across the issue with coal blocks simply disappearing, regardless if I was holding redstone in my hand or not. And even if I was, it would not give me Soot-covered Redstone. I disabled the mod and the issue of coal blocks simply disappearing when left clicked was gone.

But interestingly enough, if I placed down coal blocks when the mod was disabled, then logged back in with the mod enabled, I would then get soot-covered redstone, and those coal blocks would not disappear 

Now when I was "testing" it with it isolated from other mods (aside from fabric API and fabric kotlin of course), I would launch, create world, then soon after spawning in, I would crash.

`[23:38:31] [main/INFO]: Loading for game Minecraft 1.17
[23:38:32] [main/INFO]: [FabricLoader] Loading 67 mods: fabric-renderer-api-v1@0.4.3+676f40fa3d, fabric-keybindings-v0@0.2.2+36b77c3e3d, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1, fabric-structure-api-v1@1.1.10+be9da3103d, fabric-containers-v0@0.1.12+a02b44633d, dml-refabricated-events@0.4.0-alpha1, fabric-dimensions-v1@2.0.10+a02b44633d, fabric-object-builder-api-v1@1.10.9+b7ab61213d, java@16, fabric-game-rule-api-v1@1.0.6+a02b44633d, dml-refabricated-modular-armor@0.4.0-alpha1, fabric-api-base@0.3.0+a02b44633d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1, fabric-rendering-data-attachment-v1@0.1.5+a02b44633d, fabric-textures-v0@1.0.6+a02b44633d, fabric-rendering-fluids-v1@0.1.13+a02b44633d, dml-refabricated-base@0.4.0-alpha1, org_jetbrains_kotlin_kotlin-stdlib@1.5.10, playerabilitylib@1.3.0-nightly.1.17-rc1, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, fabric-lifecycle-events-v1@1.4.4+a02b44633d, fabric-renderer-registries-v1@3.2.0+a02b44633d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10, fabric-loot-tables-v1@1.0.4+a02b44633d, fabric@0.35.1+1.17, fabric-particles-v1@0.2.4+a02b44633d, fabric-networking-v0@0.3.2+92519afa3d, dml-refabricated@0.4.0-alpha1, fabric-api-lookup-api-v1@1.1.0+1d383bb63d, fabric-networking-blockentity-v0@0.2.11+a02b44633d, minecraft@1.17, fabric-screen-handler-api-v1@1.1.8+a02b44633d, ktdatataglib@1.5.2, dml-refabricated-rei@0.4.0-alpha1, fabric-command-api-v1@1.1.1+a02b44633d, jankson@3.0.1+j1.2.0, fabric-screen-api-v1@1.0.4+198a96213d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, fabric-renderer-indigo@0.4.8+a02b44633d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0, libninepatch@1.1.0, fabric-crash-report-info-v1@0.1.5+be9da3103d, fabric-events-interaction-v0@0.4.8+a02b44633d, fabric-item-api-v1@1.2.4+a02b44633d, com_github_nathanpb_safer@1.1.0, libgui@4.0.0-beta.4+1.17-rc1, fabric-language-kotlin@1.6.1+kotlin.1.5.10, fabric-entity-events-v1@1.1.0+a02b44633d, fabric-rendering-v0@1.1.2+92519afa3d, fabric-key-binding-api-v1@1.0.4+a02b44633d, fabric-rendering-v1@1.6.0+a02b44633d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0, fabric-resource-loader-v0@0.4.7+b7ab61213d, org_jetbrains_kotlin_kotlin-reflect@1.5.10, fabric-content-registries-v0@0.2.2+a02b44633d, fabric-tag-extensions-v0@1.1.4+a02b44633d, fabric-biome-api-v1@3.1.11+c345aea83d, fabric-commands-v0@0.2.2+92519afa3d, fabric-registry-sync-v0@0.7.10+e2961fee3d, fabric-mining-levels-v0@0.1.3+92519afa3d, fabric-networking-api-v1@1.0.11+b7ab61213d, fabric-events-lifecycle-v0@0.2.1+92519afa3d, fabric-item-groups-v0@0.2.10+b7ab61213d, fabric-models-v0@0.3.0+a02b44633d, fabric-object-builders-v0@0.7.3+a02b44633d
[23:38:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/Minecraf/Install/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[23:38:32] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[23:38:32] [main/INFO]: Compatibility level set to JAVA_16
[23:38:33] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[23:38:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:38:37] [Render thread/INFO]: Setting user: KavisKrypt
[23:38:37] [Render thread/INFO]: Trying to read config file...
[23:38:37] [Render thread/INFO]: A config file was found, loading it..
[23:38:37] [Render thread/INFO]: Successfully loaded config file.
[23:38:38] [Render thread/INFO]: [STDOUT]: Deep Mob Learning: Refabricated is good to go
[23:38:38] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[23:38:38] [Render thread/INFO]: [STDOUT]: KtDataTagLib Example Mod is running
[23:38:38] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[23:38:38] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[23:38:39] [Render thread/INFO]: Narrator library for x64 successfully loaded
[23:38:39] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), DML: Refabricated - Vanilla Events, Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), DML: Refabricated - Glitch Armor, Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), DML: Refabricated - Base, Pal, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Deep Mob Learning: Refabricated, Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), DML: Refabricated - REI Integration, Fabric Command API (v1), Jankson, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), LibGui, Fabric Language Kotlin, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[23:38:42] [Worker-Main-14/WARN]: Unable to load model: 'ktdatataglib:example_item#inventory' referenced from: ktdatataglib:example_item#inventory: java.io.FileNotFoundException: ktdatataglib:models/item/example_item.json
[23:38:42] [Worker-Main-14/WARN]: Unable to resolve texture reference: #missing in dml-refabricated:item/cafeteria
[23:38:42] [Worker-Main-14/WARN]: Unable to resolve texture reference: #missing in dml-refabricated:block/cafeteria
[23:38:42] [Worker-Main-13/ERROR]: Using missing texture, unable to load dml-refabricated:textures/block/matter_condenser.png : java.io.FileNotFoundException: dml-refabricated:textures/block/matter_condenser.png
[23:38:43] [Render thread/INFO]: OpenAL initialized.
[23:38:43] [Render thread/INFO]: Sound engine started
[23:38:43] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/blocks.png-atlas
[23:38:43] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[23:38:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:38:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:38:43] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:38:43] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:38:43] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:38:43] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[23:38:43] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:38:43] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[23:38:48] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.789 ms
[23:38:51] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:38:51] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:38:51] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:38:51] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:38:51] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:38:51] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (DML: Refabricated - Glitch Armor, DML: Refabricated - Base, Fabric Tool Attribute API (v1))
[23:38:51] [Render thread/INFO]: Loaded 10 recipes
[23:38:51] [Render thread/INFO]: Loaded 1137 advancements
[23:38:52] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:38:52] [Server thread/INFO]: Starting integrated minecraft server version 1.17
[23:38:52] [Server thread/INFO]: Generating keypair
[23:38:55] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:38:55] [Render thread/INFO]: Preparing spawn area: 0%
[23:38:56] [Render thread/INFO]: Preparing spawn area: 0%
[23:38:56] [Render thread/INFO]: Preparing spawn area: 5%
[23:38:57] [Render thread/INFO]: Preparing spawn area: 10%
[23:38:57] [Render thread/INFO]: Preparing spawn area: 14%
[23:38:58] [Render thread/INFO]: Preparing spawn area: 22%
[23:38:58] [Render thread/INFO]: Preparing spawn area: 26%
[23:38:59] [Render thread/INFO]: Preparing spawn area: 34%
[23:38:59] [Render thread/INFO]: Preparing spawn area: 38%
[23:39:00] [Render thread/INFO]: Preparing spawn area: 46%
[23:39:00] [Render thread/INFO]: Preparing spawn area: 51%
[23:39:01] [Render thread/INFO]: Preparing spawn area: 58%
[23:39:01] [Render thread/INFO]: Preparing spawn area: 63%
[23:39:02] [Render thread/INFO]: Preparing spawn area: 69%
[23:39:02] [Render thread/INFO]: Preparing spawn area: 73%
[23:39:03] [Render thread/INFO]: Preparing spawn area: 83%
[23:39:03] [Render thread/INFO]: Preparing spawn area: 87%
[23:39:04] [Render thread/INFO]: Preparing spawn area: 90%
[23:39:04] [Render thread/INFO]: Time elapsed: 8732 ms
[23:39:04] [Server thread/INFO]: Changing view distance to 11, from 10
[23:39:05] [Server thread/INFO]: KavisKrypt[local:E:ec5e5d7c] logged in with entity id 270 at (172.5, 63.0, -28.5)
[23:39:05] [Server thread/INFO]: KavisKrypt joined the game
[23:39:05] [Netty Local Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 310.6 ?s
[23:39:05] [Server thread/INFO]: Saving and pausing game...
[23:39:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[23:39:06] [Render thread/INFO]: Loaded 0 advancements
[23:39:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[23:39:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[23:39:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-1.17.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_3218 cannot be cast to class dev.nathanpb.dml.accessor.ITrialWorldPersistenceAccessor (net.minecraft.class_3218 and dev.nathanpb.dml.accessor.ITrialWorldPersistenceAccessor are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @10a9d961)
	at dev.nathanpb.dml.utils.AccessorsKt.getRunningTrials(AccessorsKt.java:28) ~[0f0bf980-23a6-40f9-95d7-2899ad98aa67.jar:?]
	at dev.nathanpb.dml.trial.TrialGriefPrevention$Companion.isBlockProtected(TrialGriefPrevention.java:51) ~[0f0bf980-23a6-40f9-95d7-2899ad98aa67.jar:?]
	at dev.nathanpb.dml.trial.TrialGriefPrevention.onEndermanTeleport(TrialGriefPrevention.java:105) ~[0f0bf980-23a6-40f9-95d7-2899ad98aa67.jar:?]
	at dev.nathanpb.dml.DeepMobLearningKt$init$1$2.invoke(DeepMobLearningKt.java:97) ~[0f0bf980-23a6-40f9-95d7-2899ad98aa67.jar:?]
	at dev.nathanpb.dml.DeepMobLearningKt$init$1$2.invoke(DeepMobLearningKt.java:97) ~[0f0bf980-23a6-40f9-95d7-2899ad98aa67.jar:?]
	at dev.nathanpb.dml.event.VanillaEventsKt$EndermanTeleportEvent$1$1.invoke(VanillaEventsKt.java:90) ~[3f09654f-5218-4395-a17b-f7a9f57b3d1c.jar:?]
	at dev.nathanpb.dml.event.VanillaEventsKt$EndermanTeleportEvent$1$1.invoke(VanillaEventsKt.java:89) ~[3f09654f-5218-4395-a17b-f7a9f57b3d1c.jar:?]
	at net.minecraft.class_1560.handler$zid000$teleport(class_1560.java:1039) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1560.method_7024(class_1560.java) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1560.method_7029(class_1560.java:280) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1560.method_5643(class_1560.java:366) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2671) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:538) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1588.method_6007(class_1588.java:43) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1560.method_6007(class_1560.java:249) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2342) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:338) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:656) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:483) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:418) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:393) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893) ~[intermediary-1.17.jar:?]
	... 5 more
[23:39:07] [Server thread/ERROR]: This crash report has been saved to: E:\Minecraf\Instances\Test single\crash-reports\crash-2021-06-12_23.39.07-server.txt
[23:39:07] [Server thread/INFO]: Stopping server
[23:39:07] [Server thread/INFO]: Saving players
[23:39:07] [Server thread/INFO]: KavisKrypt lost connection: Disconnected
[23:39:07] [Server thread/INFO]: KavisKrypt left the game`

**Comment by NathanPB** [comment]
That's expected for the alpha1, I forgot to include some mixing and had this issue.

It's fixed in alpha2 that should be released in any time today, so I will be closing this

Thanks for reporting
