### ISSUE TITLE
Alpha 2 Report | Ghast Fireball

### ISSUE THREAD

**Issue by KavisKryptic** [NathanPB/DeepMobLearning-Refabricated#46]
I found this out when I was testing in the trial [Nether mobs; Advanced] 

When a Ghast shoots a fireball, from what I noticed, just before impacting the ground it causes a crash. 

Here are the logs, hope it helps!

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 6/13/21, 8:50 PM
Description: Ticking entity

java.lang.NullPointerException: Parameter specified as non-null is null: method dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke, parameter entity
	at dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke(VanillaEventsKt.java)
	at dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke(VanillaEventsKt.java:96)
	at net.minecraft.class_3218.handler$zih000$explode(class_3218.java:2602)
	at net.minecraft.class_3218.method_8454(class_3218.java)
	at net.minecraft.class_1937.method_8537(class_1937.java:499)
	at net.minecraft.class_1674.method_7488(class_1674.java:32)
	at net.minecraft.class_1668.method_5773(class_1668.java:76)
	at net.minecraft.class_3218.method_18762(class_3218.java:656)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:418)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:393)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke(VanillaEventsKt.java)
	at dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke(VanillaEventsKt.java:96)
	at net.minecraft.class_3218.handler$zih000$explode(class_3218.java:2602)
	at net.minecraft.class_3218.method_8454(class_3218.java)
	at net.minecraft.class_1937.method_8537(class_1937.java:499)
	at net.minecraft.class_1674.method_7488(class_1674.java:32)
	at net.minecraft.class_1668.method_5773(class_1668.java:76)
	at net.minecraft.class_3218.method_18762(class_3218.java:656)

-- Entity being ticked --
Details:
	Entity Type: minecraft:fireball (net.minecraft.class_1674)
	Entity ID: 1403
	Entity Name: Fireball
	Entity's Exact location: -348.50, 72.08, 143.50
	Entity's Block location: World: (-349,72,143), Section: (at 3,8,15 in -22,4,8; chunk contains blocks -352,0,128 to -337,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.34, -0.44, 0.13
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:418)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:393)

-- Affected level --
Details:
	All players: 1 total; [class_3222['KavisKrypt'/352, l='ServerLevel[New World]', x=-347.66, y=71.00, z=142.98]]
	Chunk stats: 2600
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,65,80), Section: (at 0,1,0 in -14,4,5; chunk contains blocks -224,0,80 to -209,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1193 game time, 1193 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 110868 (now: false), thunder time: 109882 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 435936240 bytes (415 MiB) / 1509949440 bytes (1440 MiB) up to 7885291520 bytes (7520 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6079
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37580.14
	Virtual memory used (MB): 20115.83
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 17.04
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7520m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		com_github_nathanpb_safer: Safer 1.1.0
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.0-alpha2
		dml-refabricated-base: DML: Refabricated - Base 0.4.0-alpha2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.0-alpha2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.0-alpha2
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.0-alpha2
		fabric: Fabric API 0.35.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.10+be9da3103d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.3
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		ktdatataglib: KtDataTagLib 1.5.2
		libgui: LibGui 4.0.0-beta.4+1.17-rc1
		libninepatch: LibNinePatch 1.1.0
		minecraft: Minecraft 1.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
	Player Count: 1 / 8; [class_3222['KavisKrypt'/352, l='ServerLevel[New World]', x=-347.66, y=71.00, z=142.98]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

```
[20:48:32] [main/INFO]: Loading for game Minecraft 1.17
[20:48:33] [main/INFO]: [FabricLoader] Loading 67 mods: fabric-renderer-api-v1@0.4.3+676f40fa3d, fabric-keybindings-v0@0.2.2+36b77c3e3d, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1, fabric-structure-api-v1@1.1.10+be9da3103d, fabric-containers-v0@0.1.12+a02b44633d, dml-refabricated-events@0.4.0-alpha2, fabric-dimensions-v1@2.0.10+a02b44633d, fabric-object-builder-api-v1@1.10.9+b7ab61213d, java@16, fabric-game-rule-api-v1@1.0.6+a02b44633d, dml-refabricated-modular-armor@0.4.0-alpha2, fabric-api-base@0.3.0+a02b44633d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1, fabric-rendering-data-attachment-v1@0.1.5+a02b44633d, fabric-textures-v0@1.0.6+a02b44633d, fabric-rendering-fluids-v1@0.1.13+a02b44633d, dml-refabricated-base@0.4.0-alpha2, org_jetbrains_kotlin_kotlin-stdlib@1.5.10, playerabilitylib@1.3.0-nightly.1.17-rc1, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, fabric-lifecycle-events-v1@1.4.4+a02b44633d, fabric-renderer-registries-v1@3.2.0+a02b44633d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10, fabric-loot-tables-v1@1.0.4+a02b44633d, fabric@0.35.1+1.17, fabric-particles-v1@0.2.4+a02b44633d, fabric-networking-v0@0.3.2+92519afa3d, dml-refabricated@0.4.0-alpha2, fabric-api-lookup-api-v1@1.1.0+1d383bb63d, fabric-networking-blockentity-v0@0.2.11+a02b44633d, minecraft@1.17, fabric-screen-handler-api-v1@1.1.8+a02b44633d, ktdatataglib@1.5.2, dml-refabricated-rei@0.4.0-alpha2, fabric-command-api-v1@1.1.1+a02b44633d, jankson@3.0.1+j1.2.0, fabric-screen-api-v1@1.0.4+198a96213d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, fabric-renderer-indigo@0.4.8+a02b44633d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0, libninepatch@1.1.0, fabric-crash-report-info-v1@0.1.5+be9da3103d, fabric-events-interaction-v0@0.4.8+a02b44633d, fabric-item-api-v1@1.2.4+a02b44633d, libgui@4.0.0-beta.4+1.17-rc1, com_github_nathanpb_safer@1.1.0, fabric-language-kotlin@1.6.1+kotlin.1.5.10, fabric-entity-events-v1@1.1.0+a02b44633d, fabric-rendering-v0@1.1.2+92519afa3d, fabric-key-binding-api-v1@1.0.4+a02b44633d, fabric-rendering-v1@1.6.0+a02b44633d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0, fabric-resource-loader-v0@0.4.7+b7ab61213d, org_jetbrains_kotlin_kotlin-reflect@1.5.10, fabric-content-registries-v0@0.2.2+a02b44633d, fabric-tag-extensions-v0@1.1.4+a02b44633d, fabric-biome-api-v1@3.1.11+c345aea83d, fabric-commands-v0@0.2.2+92519afa3d, fabric-registry-sync-v0@0.7.10+e2961fee3d, fabric-mining-levels-v0@0.1.3+92519afa3d, fabric-networking-api-v1@1.0.11+b7ab61213d, fabric-events-lifecycle-v0@0.2.1+92519afa3d, fabric-item-groups-v0@0.2.10+b7ab61213d, fabric-models-v0@0.3.0+a02b44633d, fabric-object-builders-v0@0.7.3+a02b44633d
[20:48:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/Minecraf/Install/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[20:48:33] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[20:48:33] [main/INFO]: Compatibility level set to JAVA_16
[20:48:34] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[20:48:38] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:48:39] [Render thread/INFO]: Setting user: KavisKrypt
[20:48:39] [Render thread/INFO]: Trying to read config file...
[20:48:39] [Render thread/INFO]: A config file was found, loading it..
[20:48:39] [Render thread/INFO]: Successfully loaded config file.
[20:48:39] [Render thread/INFO]: [STDOUT]: Deep Mob Learning: Refabricated is good to go
[20:48:39] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:48:39] [Render thread/INFO]: [STDOUT]: KtDataTagLib Example Mod is running
[20:48:39] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[20:48:39] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[20:48:41] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:48:41] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), DML: Refabricated - Vanilla Events, Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), DML: Refabricated - Glitch Armor, Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), DML: Refabricated - Base, Pal, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Deep Mob Learning: Refabricated, Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), DML: Refabricated - REI Integration, Fabric Command API (v1), Jankson, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), LibGui, Fabric Language Kotlin, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[20:48:43] [Worker-Main-14/WARN]: Unable to load model: 'ktdatataglib:example_item#inventory' referenced from: ktdatataglib:example_item#inventory: java.io.FileNotFoundException: ktdatataglib:models/item/example_item.json
[20:48:43] [Worker-Main-14/WARN]: Unable to resolve texture reference: #missing in dml-refabricated:item/cafeteria
[20:48:43] [Worker-Main-14/WARN]: Unable to resolve texture reference: #missing in dml-refabricated:block/cafeteria
[20:48:44] [Render thread/INFO]: OpenAL initialized.
[20:48:44] [Render thread/INFO]: Sound engine started
[20:48:44] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:48:44] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:48:44] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:48:44] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:48:44] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:48:44] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:48:44] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:48:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:48:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:48:45] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:49:00] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.416 ms
[20:49:04] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:49:04] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:49:04] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:49:04] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:49:04] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:49:04] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (DML: Refabricated - Glitch Armor, DML: Refabricated - Base, Fabric Tool Attribute API (v1))
[20:49:05] [Render thread/INFO]: Loaded 10 recipes
[20:49:05] [Render thread/INFO]: Loaded 1137 advancements
[20:49:06] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:49:06] [Server thread/INFO]: Starting integrated minecraft server version 1.17
[20:49:06] [Server thread/INFO]: Generating keypair
[20:49:09] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:49:09] [Render thread/INFO]: Preparing spawn area: 0%
[20:49:09] [Render thread/INFO]: Preparing spawn area: 1%
[20:49:10] [Render thread/INFO]: Preparing spawn area: 6%
[20:49:10] [Render thread/INFO]: Preparing spawn area: 12%
[20:49:11] [Render thread/INFO]: Preparing spawn area: 16%
[20:49:11] [Render thread/INFO]: Preparing spawn area: 26%
[20:49:12] [Render thread/INFO]: Preparing spawn area: 33%
[20:49:12] [Render thread/INFO]: Preparing spawn area: 42%
[20:49:13] [Render thread/INFO]: Preparing spawn area: 46%
[20:49:13] [Render thread/INFO]: Preparing spawn area: 57%
[20:49:14] [Render thread/INFO]: Preparing spawn area: 64%
[20:49:14] [Render thread/INFO]: Preparing spawn area: 70%
[20:49:15] [Render thread/INFO]: Preparing spawn area: 79%
[20:49:15] [Render thread/INFO]: Preparing spawn area: 87%
[20:49:16] [Render thread/INFO]: Preparing spawn area: 96%
[20:49:16] [Render thread/INFO]: Time elapsed: 7181 ms
[20:49:16] [Server thread/INFO]: Changing view distance to 11, from 10
[20:49:17] [Server thread/INFO]: KavisKrypt[local:E:f5d7baac] logged in with entity id 352 at (-233.5, 66.0, 90.5)
[20:49:17] [Server thread/INFO]: KavisKrypt joined the game
[20:49:17] [Netty Local Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 257.2 ?s
[20:49:17] [Server thread/INFO]: Saving and pausing game...
[20:49:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[20:49:18] [Render thread/INFO]: Loaded 0 advancements
[20:49:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[20:49:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[20:50:14] [Server thread/INFO]: [KavisKrypt: Set own game mode to Survival Mode]
[20:50:14] [Render thread/INFO]: [CHAT] Set own game mode to Survival Mode
[20:50:16] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-1.17.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke, parameter entity
	at dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke(VanillaEventsKt.java) ~[bc4df087-7c91-489a-addb-7c2c534f6c81.jar:?]
	at dev.nathanpb.dml.event.VanillaEventsKt$WorldExplosionEvent$1$1.invoke(VanillaEventsKt.java:96) ~[bc4df087-7c91-489a-addb-7c2c534f6c81.jar:?]
	at net.minecraft.class_3218.handler$zih000$explode(class_3218.java:2602) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_8454(class_3218.java) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1937.method_8537(class_1937.java:499) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1674.method_7488(class_1674.java:32) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1668.method_5773(class_1668.java:76) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:656) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:483) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:418) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:393) ~[intermediary-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893) ~[intermediary-1.17.jar:?]
	... 5 more
[20:50:16] [Server thread/ERROR]: This crash report has been saved to: E:\Minecraf\Instances\Test single\crash-reports\crash-2021-06-13_20.50.16-server.txt
[20:50:16] [Server thread/INFO]: Stopping server
[20:50:16] [Server thread/INFO]: Saving players

```

**Comment by NathanPB** [comment]
Same issue as the previous #45, thanks again. I will close this one because it's the same crash report as the previous
