### ISSUE TITLE
Server Crash: Cannot invoke "net.minecraft.util.math.BlockPos.getY()" because "â˜ƒ" is null

### ISSUE THREAD

**Issue by dandin87** [NathanPB/DeepMobLearning-Refabricated#51]
All Of Fabric 4 Public Server. When ever the player fighting the system glitch joins the server, the server crashes with this error. This started when the system glitch killed them and I assume they used /back to return and loaded that chunk now crashes. There was also this unknown attribute error in the logs before the player died. Not sure if it is the System Glitch's attribute or unrelated. 
[14:50:27] [Server thread/WARN]: Ignoring unknown attribute 'generic.movementSpeed'
[14:52:20] [Server thread/INFO]: ajoene was slain by entity.dml-refabricated.system_glitch
[14:52:24] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.crash.CrashException: Ticking entity
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.math.BlockPos.getY()" because "â˜ƒ" is null
	at net.minecraft.world.HeightLimitView.isOutOfHeightLimit(HeightLimitView.java:41) ~[intermediary-server.jar:?]
	at net.minecraft.world.World.getBlockEntity(World.java:514) ~[intermediary-server.jar:?]
	at dev.nathanpb.dml.entity.SystemGlitchEntity.applyDamage(SystemGlitchEntity.java:179) ~[56f14d1f-1962-48ef-a78e-e7c49abf7e64.jar:?]
	at net.minecraft.entity.LivingEntity.damage(LivingEntity.java:1099) ~[intermediary-server.jar:?]
	at net.minecraft.entity.LivingEntity.handleFallDamage(LivingEntity.java:1519) ~[intermediary-server.jar:?]
	at net.minecraft.block.Block.onLandedUpon(Block.java:464) ~[intermediary-server.jar:?]
Mapped Crash Report
https://paste.alloffabric.com/jemegereko.yaml
Mapped Log 
https://paste.alloffabric.com/apudoqeyad.properties

**Comment by NathanPB** [comment]
lmao this is looking like a vanilla problem, but I'm going to make a fix to avoid that on DML

**Comment by NathanPB** [comment]
It was not a vanilla problem
