### ISSUE TITLE
Client crash on trying to insert model into deep learner.

### ISSUE THREAD

**Issue by frikinjay** [NathanPB/DeepMobLearning-Refabricated#70]
Using 0.5.0 beta 2

```
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2945$class_2946.method_12794()" because the return value of "net.minecraft.class_2945.method_12783(net.minecraft.class_2940)" is null
	at net.minecraft.class_2945.method_12789(class_2945.java:118)
	at net.minecraft.class_1639.method_6109(com/github/galatynf/sihywtcamd/mixin/WitherSkeletonMixin.java [sihywtcamd.mixins.json]:42)
	at net.minecraft.class_1309.method_17825(class_1309.java:557)
	at net.minecraft.class_1639.method_18394(com/github/galatynf/sihywtcamd/mixin/WitherSkeletonMixin.java [sihywtcamd.mixins.json]:73)
	at net.minecraft.class_1309.method_18378(class_1309.java:3317)
	at net.minecraft.class_1297.<init>(class_1297.java:287)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1308.<init>(class_1308.java:128)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1588.<init>(class_1588.java:30)
	at net.minecraft.class_1547.<init>(class_1547.java:67)
	at net.minecraft.class_1639.<init>(class_1639.java:33)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at dev.nathanpb.dml.screen.handler.widget.WEntityShowcase.paint(WEntityShowcase.kt:43)
	at io.github.cottonmc.cotton.gui.widget.WPanel.paint(WPanel.java:140)
	at io.github.cottonmc.cotton.gui.client.CottonInventoryScreen.paint(CottonInventoryScreen.java:273)
	at io.github.cottonmc.cotton.gui.client.CottonInventoryScreen.method_25394(CottonInventoryScreen.java:282)
	at net.minecraft.class_757.redirect$fck000$onRenderCurrentScreen(de/keksuccino/konkrete/events/client/mixins/MixinGameRenderer.java [konkrete.mixins.events.client.json]:38)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2945.method_12789(class_2945.java:118)
	at net.minecraft.class_1639.method_6109(com/github/galatynf/sihywtcamd/mixin/WitherSkeletonMixin.java [sihywtcamd.mixins.json]:42)
	at net.minecraft.class_1309.method_17825(class_1309.java:557)
	at net.minecraft.class_1639.method_18394(com/github/galatynf/sihywtcamd/mixin/WitherSkeletonMixin.java [sihywtcamd.mixins.json]:73)
	at net.minecraft.class_1309.method_18378(class_1309.java:3317)
	at net.minecraft.class_1297.<init>(class_1297.java:287)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1308.<init>(class_1308.java:128)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1588.<init>(class_1588.java:30)
	at net.minecraft.class_1547.<init>(class_1547.java:67)
	at net.minecraft.class_1639.<init>(class_1639.java:33)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at dev.nathanpb.dml.screen.handler.widget.WEntityShowcase.paint(WEntityShowcase.kt:43)
	at io.github.cottonmc.cotton.gui.widget.WPanel.paint(WPanel.java:140)
	at io.github.cottonmc.cotton.gui.client.CottonInventoryScreen.paint(CottonInventoryScreen.java:273)
	at io.github.cottonmc.cotton.gui.client.CottonInventoryScreen.method_25394(CottonInventoryScreen.java:282)
	at net.minecraft.class_757.redirect$fck000$onRenderCurrentScreen(de/keksuccino/konkrete/events/client/mixins/MixinGameRenderer.java [konkrete.mixins.events.client.json]:38)

-- Screen render details --
Details:
	Screen name: io.github.cottonmc.cotton.gui.client.CottonInventoryScreen
	Mouse location: Scaled: (320, 175). Absolute: (960.000000, 527.000000)
	Screen size: Scaled: (640, 352). Absolute: (1920, 1055). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['frikinjay'/1916, l='ClientLevel', x=-50.81, y=74.00, z=241.03]]
	Chunk stats: 1024, 464
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,73,256), Section: (at 0,9,0 in -2,4,16; chunk contains blocks -32,-64,256 to -17,319,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 389956 game time, 320734 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Luligabi1** [comment]
Upon closer inspection, two other mods are recorded onto the crash report, those being:

1. [So I heard you were talking crap about Minecraft's Difficulty](https://www.curseforge.com/minecraft/mc-mods/sihywtcamd)
2. [Konkrete [Fabric]](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric)

Are you still able to reproduce the crash without these mods?

**Comment by frikinjay** [comment]
It was working fine with those 2 mods installed previously and i havent updated them since. I did update other mods that arent mentioned anywhere in the log.

**Comment by Luligabi1** [comment]
> It was working fine with those 2 mods installed previously and i havent updated them since. I did update other mods that arent mentioned anywhere in the log.

Can you try reproducing the glitch without the 2 mods? If you're unable, please describe how you triggered it the first time.
